#ifndef STATUS_H
#define STATUS_H

// HTTP Status Codes as defined by IANA
// Reference:
// >    https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

#define CTTP_STATUS_CONTINUE                        "100 Continue"
#define CTTP_STATUS_SWITCHING_PROTOCOLS             "101 Switching Protocols"
#define CTTP_STATUS_PROCESSING                      "102 Processing"
#define CTTP_STATUS_HEARLY_HINTS                    "103 Early Hints"

#define CTTP_STATUS_OK                              "200 OK"
#define CTTP_STATUS_CREATED                         "201 Created"
#define CTTP_STATUS_ACCEPTED                        "202 Accepted"
#define CTTP_STATUS_NON_AUTHORITATIVE               "203 Non-Authoritative Information"
#define CTTP_STATUS_NO_CONTENT                      "204 No Content"
#define CTTP_STATUS_RESET_CONTENT                   "205 Reset Content"
#define CTTP_STATUS_PARTIAL_CONTENT                 "206 Partial Content"
#define CTTP_STATUS_MULTI_STATUS                    "207 Multi-Status"
#define CTTP_STATUS_ALREADY_REPORTED                "208 Already Reported"
#define CTTP_STATUS_IM_USED                         "226 IM Used"

#define CTTP_STATUS_MULTIPLE_CHOICES                "300 Multiple Choices"
#define CTTP_STATUS_MOVED_PERMANENTLY               "301 Moved Permanently"
#define CTTP_STATUS_FOUND                           "302 Found"
#define CTTP_STATUS_SEE_OTHER                       "303 See Other"
#define CTTP_STATUS_NOT_MODIFIED                    "304 Not Modified"
#define CTTP_STATUS_USE_PROXY                       "305 Use Proxy"
#define CTTP_STATUS_TEMPORARY_REDIRECT              "307 Temporary Redirect"
#define CTTP_STATUS_PERMANENT_REDIRECT              "308 Permanent Redirect"

#define CTTP_STATUS_BAD_REQUEST                     "400 Bad Request"
#define CTTP_STATUS_UNAUTHORIZED                    "401 Unauthorized"
#define CTTP_STATUS_PAYMENT_REQUIRED                "402 Payment Required"
#define CTTP_STATUS_FORBIDDEN                       "403 Forbidden"
#define CTTP_STATUS_NOT_FOUND                       "404 Not Found"
#define CTTP_STATUS_METHOD_NOT_ALLOWED              "405 Method Not Allowed"
#define CTTP_STATUS_NOT_ACCEPTABLE                  "406 Not Acceptable"
#define CTTP_STATUS_PROXY_AUTH_REQUIRED             "407 Proxy Authentication Required"
#define CTTP_STATUS_REQUEST_TIMEOUT                 "408 Request Timeout"
#define CTTP_STATUS_CONFLICT                        "409 Conflict"
#define CTTP_STATUS_GONE                            "410 Gone"
#define CTTP_STATUS_LENGTH_REQUIRED                 "411 Length Required"
#define CTTP_STATUS_PRECONDITION_FAILED             "412 Precondition Failed"
#define CTTP_STATUS_CONTENT_TOO_LARGE               "413 Content Too Large"
#define CTTP_STATUS_URI_TOO_LONG                    "414 URI Too Long"
#define CTTP_STATUS_UNSUPPORTED_MEDIA               "415 Unsupported Media Type"
#define CTTP_STATUS_RANGE_NOT_SATISFY               "416 Range Not Satisfiable"
#define CTTP_STATUS_EXPECTATION_FAILED              "417 Expectation Failed"
#define CTTP_STATUS_IM_A_TEAPOT                     "418 I'm a teapot"
#define CTTP_STATUS_MISDIRECTED_REQUEST             "421 Misdirected Request"
#define CTTP_STATUS_UNPROCESSABLE_ENTITY            "422 Unprocessable Entity"
#define CTTP_STATUS_LOCKED                          "423 Locked"
#define CTTP_STATUS_FAILED_DEPENDENCY               "424 Failed Dependency"
#define CTTP_STATUS_TOO_EARLY                       "425 Too Early"
#define CTTP_STATUS_UPGRADE_REQUIRED                "426 Upgrade Required"
#define CTTP_STATUS_PRECONDITION_REQUIRED           "428 Precondition Required"
#define CTTP_STATUS_TOO_MANY_REQUESTS               "429 Too Many Requests"
#define CTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE "431 Request Header Fields Too Large"
#define CTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS   "451 Unavailable For Legal Reasons"

#define CTTP_STATUS_INTERNAL_SERVER_ERROR           "500 Internal Server Error"
#define CTTP_STATUS_NOT_IMPLEMENTED                 "501 Not Implemented"
#define CTTP_STATUS_BAD_GATEWAY                     "502 Bad Gateway"
#define CTTP_STATUS_SERVICE_UNAVAILABLE             "503 Service Unavailable"
#define CTTP_STATUS_GATEWAY_TIMEOUT                 "504 Gateway Timeout"
#define CTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED      "505 HTTP Version Not Supported"
#define CTTP_STATUS_VARIANT_ALSO_NEGOTIATES         "506 Variant Also Negotiates"
#define CTTP_STATUS_INSUFFICIENT_STORAGE            "507 Insufficient Storage"
#define CTTP_STATUS_LOOP_DETECTED                   "508 Loop Detected"
#define CTTP_STATUS_NOT_EXTENDED                    "510 Not Extended"
#define CTTP_STATUS_NETWORK_AUTH_REQUIRED           "511 Network Authentication Required"

// MESSAGES

#define CTTP_MESSAGE_CONTINUE                        "Continue"
#define CTTP_MESSAGE_SWITCHING_PROTOCOLS             "Switching Protocols"
#define CTTP_MESSAGE_PROCESSING                      "Processing"
#define CTTP_MESSAGE_HEARLY_HINTS                    "Early Hints"

#define CTTP_MESSAGE_OK                              "OK"
#define CTTP_MESSAGE_CREATED                         "Created"
#define CTTP_MESSAGE_ACCEPTED                        "Accepted"
#define CTTP_MESSAGE_NON_AUTHORITATIVE               "Non-Authoritative Information"
#define CTTP_MESSAGE_NO_CONTENT                      "No Content"
#define CTTP_MESSAGE_RESET_CONTENT                   "Reset Content"
#define CTTP_MESSAGE_PARTIAL_CONTENT                 "Partial Content"
#define CTTP_MESSAGE_MULTI_STATUS                    "Multi-Status"
#define CTTP_MESSAGE_ALREADY_REPORTED                "Already Reported"
#define CTTP_MESSAGE_IM_USED                         "IM Used"

#define CTTP_MESSAGE_MULTIPLE_CHOICES                "Multiple Choices"
#define CTTP_MESSAGE_MOVED_PERMANENTLY               "Moved Permanently"
#define CTTP_MESSAGE_FOUND                           "Found"
#define CTTP_MESSAGE_SEE_OTHER                       "See Other"
#define CTTP_MESSAGE_NOT_MODIFIED                    "Not Modified"
#define CTTP_MESSAGE_USE_PROXY                       "Use Proxy"
#define CTTP_MESSAGE_TEMPORARY_REDIRECT              "Temporary Redirect"
#define CTTP_MESSAGE_PERMANENT_REDIRECT              "Permanent Redirect"

#define CTTP_MESSAGE_BAD_REQUEST                     "Bad Request"
#define CTTP_MESSAGE_UNAUTHORIZED                    "Unauthorized"
#define CTTP_MESSAGE_PAYMENT_REQUIRED                "Payment Required"
#define CTTP_MESSAGE_FORBIDDEN                       "Forbidden"
#define CTTP_MESSAGE_NOT_FOUND                       "Not Found"
#define CTTP_MESSAGE_METHOD_NOT_ALLOWED              "Method Not Allowed"
#define CTTP_MESSAGE_NOT_ACCEPTABLE                  "Not Acceptable"
#define CTTP_MESSAGE_PROXY_AUTH_REQUIRED             "Proxy Authentication Required"
#define CTTP_MESSAGE_REQUEST_TIMEOUT                 "Request Timeout"
#define CTTP_MESSAGE_CONFLICT                        "Conflict"
#define CTTP_MESSAGE_GONE                            "Gone"
#define CTTP_MESSAGE_LENGTH_REQUIRED                 "Length Required"
#define CTTP_MESSAGE_PRECONDITION_FAILED             "Precondition Failed"
#define CTTP_MESSAGE_CONTENT_TOO_LARGE               "Content Too Large"
#define CTTP_MESSAGE_URI_TOO_LONG                    "URI Too Long"
#define CTTP_MESSAGE_UNSUPPORTED_MEDIA               "Unsupported Media Type"
#define CTTP_MESSAGE_RANGE_NOT_SATISFY               "Range Not Satisfiable"
#define CTTP_MESSAGE_EXPECTATION_FAILED              "Expectation Failed"
#define CTTP_MESSAGE_IM_A_TEAPOT                     "I'm a teapot"
#define CTTP_MESSAGE_MISDIRECTED_REQUEST             "Misdirected Request"
#define CTTP_MESSAGE_UNPROCESSABLE_ENTITY            "Unprocessable Entity"
#define CTTP_MESSAGE_LOCKED                          "Locked"
#define CTTP_MESSAGE_FAILED_DEPENDENCY               "Failed Dependency"
#define CTTP_MESSAGE_TOO_EARLY                       "Too Early"
#define CTTP_MESSAGE_UPGRADE_REQUIRED                "Upgrade Required"
#define CTTP_MESSAGE_PRECONDITION_REQUIRED           "Precondition Required"
#define CTTP_MESSAGE_TOO_MANY_REQUESTS               "Too Many Requests"
#define CTTP_MESSAGE_REQUEST_HEADER_FIELDS_TOO_LARGE "Request Header Fields Too Large"
#define CTTP_MESSAGE_UNAVAILABLE_FOR_LEGAL_REASONS   "Unavailable For Legal Reasons"

#define CTTP_MESSAGE_INTERNAL_SERVER_ERROR           "Internal Server Error"
#define CTTP_MESSAGE_NOT_IMPLEMENTED                 "Not Implemented"
#define CTTP_MESSAGE_BAD_GATEWAY                     "Bad Gateway"
#define CTTP_MESSAGE_SERVICE_UNAVAILABLE             "Service Unavailable"
#define CTTP_MESSAGE_GATEWAY_TIMEOUT                 "Gateway Timeout"
#define CTTP_MESSAGE_HTTP_VERSION_NOT_SUPPORTED      "HTTP Version Not Supported"
#define CTTP_MESSAGE_VARIANT_ALSO_NEGOTIATES         "Variant Also Negotiates"
#define CTTP_MESSAGE_INSUFFICIENT_STORAGE            "Insufficient Storage"
#define CTTP_MESSAGE_LOOP_DETECTED                   "Loop Detected"
#define CTTP_MESSAGE_NOT_EXTENDED                    "Not Extended"
#define CTTP_MESSAGE_NETWORK_AUTH_REQUIRED           "Network Authentication Required"

#endif
